<?php
define("BASE_URL","http://localhost/rlab/");
define("HOST","localhost");
define("USER","root");
define("PASS","");
define("DB","rlab");
define("CHARSET","charset=utf8");
define("TITLE","RLAB");
define("MONEDA","MXN");
define("CLIENT_ID","");
?>